lockable middleware
retailcrm/service-bundle pull request #5
Opened 2021-03-31 14:27 UTC by iyzoer

2021-04-06 12:14 UTC, gwinn requested changes

2021-04-06 12:14 UTC, gwinn commented on Messenger/Middleware/LockableMessageMiddleware.php
> +    /**
Как по мне так избыточно, хватит стандартной функции hash

2021-04-06 12:14 UTC, gwinn commented on Messenger/Middleware/LockableMessageMiddleware.php
> +            $lock = $this->lockFactory->createLock($this->hash($message), null);
```suggestion
            $lock = $this->lockFactory->createLock(hash('ripemd160', serialize($message)), null);
```

2021-04-14 10:35 UTC, Neur0toxine commented on Messenger/Middleware/LockableMessageMiddleware.php
> +        return md5(serialize($message));
```suggestion
        return hash('crc32c', serialize($message));
```

2021-04-16 06:46 UTC, iyzoer commented on Messenger/Middleware/LockableMessageMiddleware.php
> +        return hash('crc32c', serialize($message));
```suggestion
        return hash('crc32', serialize($message));
```

2021-04-16 10:35 UTC, iyzoer commented on Messenger/Middleware/LockableMessageMiddleware.php
> +    private function hash(LockableMessage $message): string
```suggestion
    private function objectHash(LockableMessage $message): string
```

2021-04-16 10:35 UTC, iyzoer commented on Messenger/Middleware/LockableMessageMiddleware.php
> +            $lock = $this->lockFactory->createLock($this->hash($message), null);
```suggestion
            $lock = $this->lockFactory->createLock($this->objectHash($message), null);
```

2021-04-16 10:37 UTC, gwinn approved these changes

2021-04-16 10:37 UTC, merged